declare const styles: {
  container: string;
  title: string;
  subTitle: string;
  subTitleItems: string;
  items: string;
  subItems: string;
  noStock: string;
  search: string;
  searchContaier: string;
  table: string;
  tableContainer: string;
  formGroup: string;
  formControl: string;
  nextBtn: string;
  containerII: string;
  bigSpace: string;
  smallSpace: string;
  cardsContainer: string;
  card: string;
  cardHover: string;
  noAdds: string;
  input: string;
  formContainer: string;
  form: string;
  link: string;
  card2: string;
  text: string;
  items2: string;
  itemsGroups: string;
  groups: string;
  subTitle2: string;
};

export default styles;
